server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: yuntu-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.remote.host:127.0.0.1}:3306/yuntu
    username: root
    password: 20030219
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    # aaa"
    version: v1.0
    group:
      test1:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.ljw.yuntubackend.controller