server:
  port: 8123
  servlet:
    context-path: /api
spring:
  config:
    import: classpath:application-dev.yaml
  application:
    name: yuntu-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.remote.host:180.184.76.60}:3306/yun_tu
    username: ${server.remote.mysql.username}
    password: ${server.remote.mysql.password}
mybatis-plus:
  configuration:
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 阿里 OSS对象存储服务
oss:
  client:
    region: ${server.oss.region}
    endpoint: ${server.oss.endpoint}
    bucketName: ${server.oss.bucketName}
    access-key-id: ${server.oss.access-key-id}
    access-key-secret: ${server.oss.access-key-secret}
tos:
  client:
    accessKey: ${server.tos.accessKey}
    secretKey: ${server.tos.secretKey}
    region: ${server.tos.region}
    bucketName: ${server.tos.bucketName}
    endpoint: ${server.tos.endpoint}
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    # aaa"
    version: v1.0
    group:
      test1:
        api-rule: package
        api-rule-resources:
          - com.ljw.yuntubackend.controller